name: 🐛 Bug
description: File a bug report here
labels: ["bug"]
assignees: devantler
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this bug report hasn't already been submitted by someone else by looking through other open/closed issues.

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Give a brief description of the bug
