name: 🐛Bug Report
description: File a bug report here
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this bug report hasn't already been submitted by someone else by looking through other open/closed issues.

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Give a brief description of the bug
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Optionally provide additional information such as logs or screenshots.
