name: 🧹 Chore
description: File a general task. For example documention, cleanup, refactoring or research.
labels: ["chore"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this chore hasn't already been submitted by someone else by looking through other open/closed issues.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the chore.
    validations:
      required: true
