name: 🧹 Chore
description: A general task that does not fit into any other category
labels: ["chore"]
assignees: devantler
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this chore hasn't already been submitted by someone else by looking through other open/closed issues.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the chore
