name: ✏️Documentation Task
description: A task related to documenting code, systems or processes
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this documentation task hasn't already been submitted by someone else by looking through other open/closed issues.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the documentation task
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Optionally provide additional information on the documentation task like diagrams, links, screenshots, etc.