name: Global Workflows

on:
  push:
    branches: [main]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 5 * * 1"
  workflow_dispatch:

jobs:
  replicate_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          patterns_to_include: ".github/workflows"
          patterns_to_ignore: ".github/workflows/global-workflows.yaml"
  replicate_renovate_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          patterns_to_include: ".github/renovate.json"
    # TODO: Await resolution of https://github.com/derberg/manage-files-in-multiple-repositories/issues/60
    # replicate_dependabot_config:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v4
    #         - uses: derberg/manage-files-in-multiple-repositories@v2
    #         with:
    #             github_token: ${{ secrets.CUSTOM_TOKEN }}
    #             patterns_to_include: '.github/dependabot.yaml'
